### ISSUE TITLE
Exception while using cypher2sql

### ISSUE THREAD

**Issue by RaniRaven** [cytosm/cytosm#21]
It seems like something very basic, so I am probably doing something wrong, but I had to devise some example on my own, since there is no documentation anywhere about how to do this cypher2sql with java. Only explanation about the process, with no piece of code, as example.
Anyhow :
using the following java code -
public static void main(String[] args) {
    String cypher_query = "MATCH (a :guild)-[:registered_in]->(k :kingdom) RETURN k.id,a.id;";
    Statement st = ASTBuilder.parse(cypher_query);
    System.out.println("Result Query : " + st.query.toString());

    try {
        Statement query = PassAvailables.parseCypher(cypher_query);
        VarDependencies vars = new VarDependencies(query);
        ScopeSelect tree = SelectTreeBuilder.createQueryTree(vars, query);
        NameSubqueries.nameSubqueries(tree);
        MoveRestrictionInPattern.moveRestrictionInPatterns(tree, vars);
        SimpleSelect s = (SimpleSelect) tree.withQueries.get(0).subquery;
        System.out.println("Got SQL(1) : " + s.toSQLString());
        System.out.println("Got SQL : " + tree.toSQLString());
    } catch (Exception exc) {
        System.out.println("Got exception : " + exc.getMessage());
        exc.printStackTrace();
    }

    //st.query.p
    CypherConverter converter = new CypherConverter();
    //CypherParser parser = new CypherParser()
    //converter.
}

results with the following exception :
Result Query : org.cytosm.cypher2sql.cypher.ast.Query@12cdcf4
Got exception : Bug found! This select doesn't select anything...
java.lang.RuntimeException: Bug found! This select doesn't select anything...
 at org.cytosm.cypher2sql.lowering.sqltree.SimpleSelect.fromItem(SimpleSelect.java:131)
 at org.cytosm.cypher2sql.lowering.sqltree.SimpleSelect.toSQLString(SimpleSelect.java:86)
 at CypherSQLTester.main(CypherSQLTester.java:29)

Process finished with exit code 0

I wouldn't even bother to put that issue, but it seems like too much work for having an error in such a trivial query, so probably something is wrong in what I am doing (I just don't know what).

I am using, by the way, the following .gtop file, not that it seems to matter to the upper exception.

{
"version" : 1.0,
"abstractionLevel" : {
    "abstractionNodes" : [ {
      "types" : [ "dragon" ],
      "attributes" : [ "id" ]
    }, {
      "types" : [ "guild" ],
      "attributes" : [ "id" ]
    }, {
      "types" : [ "kingdom" ],
      "attributes" : [ "id" ]
    } ],
    "abstractionEdges" : [ {
      "types" : [ "registered_in" ],
      "attributes" : [ ],
      "sourceType" : [ "guild" ],
      "destinationType" : [ "kingdom" ],
      "directed" : true
    }, {
      "types" : [ "owns" ],
      "attributes" : [ "since", "till" ],
      "sourceType" : [ "guild" ],
      "destinationType" : [ "dragon" ],
      "directed" : true
    }, {
      "types" : [ "fires_at" ],
      "attributes" : [ "time" ],
      "sourceType" : [ "dragon" ],
      "destinationType" : [ "dragon" ],
      "directed" : true
    } ]
  },
"implementationLevel" : {
    "graphMetadata" : {
      "backendSystem" : "RELATIONAL"
    },
    "implementationNodes" : [ {
      "types" : [ "dragon" ],
      "tableName" : "dbo.dragon_owners",
      "id" : [ {
        "columnName" : "dragon",
        "datatype" : "VARCHAR(100)",
        "concatenationPosition" : 1
      } ],
      "attributes" : [ {
        "columnName" : "dragon",
        "dataType" : "VARCHAR(100)",
        "abstractionLevelName" : "id"
      } ],
      "restrictions" : [ ]
    }, {
      "types" : [ "guild" ],
      "tableName" : "dbo.guild_in_kingdom",
      "id" : [ {
        "columnName" : "guild",
        "datatype" : "VARCHAR(100)",
        "concatenationPosition" : 1
      } ],
      "attributes" : [ {
        "columnName" : "guild",
        "dataType" : "VARCHAR(100)",
        "abstractionLevelName" : "id"
      } ],
      "restrictions" : [ ]
    }, {
      "types" : [ "kingdom" ],
      "tableName" : "dbo.guild_in_kingdom",
      "id" : [ {
        "columnName" : "kingdom",
        "datatype" : "VARCHAR(100)",
        "concatenationPosition" : 1
      } ],
      "attributes" : [ {
        "columnName" : "kingdom",
        "dataType" : "VARCHAR(100)",
        "abstractionLevelName" : "id"
      } ],
      "restrictions" : [ ]
    } ],
    "implementationEdges" : [ {
      "types" : [ "registered_in" ],
      "paths" : [ {
        "traversalHops" : [ {
          "sourceTableName" : "dbo.guild_in_kingdom",
          "sourceTableColumn" : "guild",
          "joinTableSourceColumn" : "guild",
          "joinTableName" : "dbo.guild_in_kingdom",
          "joinTableDestinationColumn" : "kingdom",
          "destinationTableColumn" : "kingdom",
          "destinationTableName" : "dbo.guild_in_kingdom",
          "attributes" : [ ]
        } ]
      } ]
    }, {
      "types" : [ "owns" ],
      "paths" : [ {
        "traversalHops" : [ {
          "sourceTableName" : "dbo.dragon_owners",
          "sourceTableColumn" : "dragon",
          "joinTableSourceColumn" : "dragon",
          "joinTableName" : "dbo.dragon_owners",
          "joinTableDestinationColumn" : "dragon",
          "destinationTableColumn" : "dragon",
          "destinationTableName" : "dbo.dragon_owners",
          "attributes" : [ {
            "columnName" : "since",
            "dataType" : "DATE",
            "abstractionLevelName" : "since"
          } , {
            "columnName" : "till",
            "dataType" : "DATE",
            "abstractionLevelName" : "till"
          }]
        } ]
      } ]
    }, {
      "types" : [ "fires_at" ],
      "paths" : [ {
        "traversalHops" : [ {
          "sourceTableName" : "fires",
          "sourceTableColumn" : "shooter",
          "joinTableSourceColumn" : "shooter",
          "joinTableName" : "fires",
          "joinTableDestinationColumn" : "shot",
          "destinationTableColumn" : "shot",
          "destinationTableName" : "fires",
          "attributes" : [ {
            "columnName" : "time",
            "dataType" : "DATE",
            "abstractionLevelName" : "time"
          } ]
        } ]
      } ]
    } ]
  }
}

**Comment by Nemikolh** [comment]
Thanks for your interest in the project!

> since there is no documentation anywhere about how to do this cypher2sql with java

Our documentation can definitely be improved! I'm sorry you had to run through so much trouble to get something working. If you know what could we change to make it better, we are happy to take pull request! :smiley:

Have you tried calling `cypher2sql` in [`PassAvailables`](https://github.com/cytosm/cytosm/blob/4e5689bddd0472c9eec082faf0e4a626ddd59fbd/cypher2sql/src/main/java/org/cytosm/cypher2sql/PassAvailables.java#L152-L169) ?

Your code would be:

```java
public static void main(String[] args) {
    String cypher_query = "MATCH (a :guild)-[:registered_in]->(k :kingdom) RETURN k.id,a.id;";

    try {
        String jsonInString = FileUtils.readFileToString(new File("path/to/file.gtop"));
        RelationalGTopInterface gtop = new RelationalGTopInterface(jsonInString);
        String sqlQuery = PassAvailables.cypher2sql(gtop, cypher_query);
        System.out.println("Got SQL : " + sqlQuery);
    } catch (Exception exc) {
        System.out.println("Got exception : " + exc.getMessage());
        exc.printStackTrace();
    }
}
```

I don't have much time right now, so I can't test it myself. If you want more examples that works, you can have a look at the tests (not usually the place you want to look at). Specifically [this file](https://github.com/cytosm/cytosm/blob/4e5689bddd0472c9eec082faf0e4a626ddd59fbd/cypher2sql/src/test/java/org/cytosm/cypher2sql/lowering/RenderingTests.java).

**Comment by RaniRaven** [comment]
o.k., that issue was solved.

However, it seems as if the abstractionlevelname is not being replaced by the implementation-level column name when translated to sql query, as I would have expected.
Do you know why ?

**Comment by Nemikolh** [comment]
We had planned to do that but this feature hasn't been implemented yet. I have created #22 to track this issue.
